import { Component, input, computed } from '@angular/core';
import { LucideAngularModule } from 'lucide-angular';
import {
  ShieldCheck,
  Lock,
  Layers,
  UserCog,
  Users,
  Stethoscope,
  UserRound,
  UserPlus,
  FileHeart,
  Search,
  CalendarCheck,
  CalendarPlus,
  Calendar,
  Clock,
  Building2,
  DoorOpen,
  LayoutGrid,
  Wrench,
  Pill,
  Package,
  BarChart3,
  ArrowLeftRight,
  AlertTriangle,
  HandHeart,
  PackageCheck,
  History,
  ClipboardList,
  Truck,
  BookUser,
  ShoppingCart,
  Star,
  FlaskConical,
  ClipboardPlus,
  FilePlus,
  ListTodo,
  FileSearch,
  FileCheck,
  Upload,
  CheckCircle,
  Printer,
  Microscope,
  Monitor,
  Settings,
  Receipt,
  FileText,
  FilePlus2,
  FileStack,
  FileX,
  Banknote,
  HandCoins,
  Landmark,
  Scale,
  Handshake,
  BookOpen,
  DollarSign,
  Send,
  Activity,
  CalendarDays,
  PieChart,
  Timer,
  TrendingUp,
  Wallet,
  GitCompareArrows,
  Eye,
  LogIn,
  ShieldAlert,
  Terminal,
  type LucideIconData,
} from 'lucide-angular';

/**
 * Mapa de iconos keyed por su nombre kebab-case.
 * Para agregar un icono nuevo, solo importalo arriba y registralo aqui.
 */
const ICON_MAP: Record<string, LucideIconData> = {
  'shield-check': ShieldCheck,
  lock: Lock,
  layers: Layers,
  'user-cog': UserCog,
  users: Users,
  stethoscope: Stethoscope,
  'user-round': UserRound,
  'user-plus': UserPlus,
  'file-heart': FileHeart,
  search: Search,
  'calendar-check': CalendarCheck,
  'calendar-plus': CalendarPlus,
  calendar: Calendar,
  clock: Clock,
  building: Building2,
  'door-open': DoorOpen,
  'layout-grid': LayoutGrid,
  wrench: Wrench,
  pill: Pill,
  package: Package,
  'bar-chart': BarChart3,
  'arrow-left-right': ArrowLeftRight,
  'alert-triangle': AlertTriangle,
  'hand-heart': HandHeart,
  'package-check': PackageCheck,
  history: History,
  'clipboard-list': ClipboardList,
  truck: Truck,
  'book-user': BookUser,
  'shopping-cart': ShoppingCart,
  star: Star,
  'flask-conical': FlaskConical,
  'clipboard-plus': ClipboardPlus,
  'file-plus': FilePlus,
  'list-todo': ListTodo,
  'file-search': FileSearch,
  'file-check': FileCheck,
  upload: Upload,
  'check-circle': CheckCircle,
  printer: Printer,
  microscope: Microscope,
  monitor: Monitor,
  settings: Settings,
  receipt: Receipt,
  'file-text': FileText,
  'file-plus-2': FilePlus2,
  'file-stack': FileStack,
  'file-x': FileX,
  banknote: Banknote,
  'hand-coins': HandCoins,
  landmark: Landmark,
  scale: Scale,
  handshake: Handshake,
  'book-open': BookOpen,
  'dollar-sign': DollarSign,
  send: Send,
  activity: Activity,
  'calendar-days': CalendarDays,
  'pie-chart': PieChart,
  timer: Timer,
  'trending-up': TrendingUp,
  wallet: Wallet,
  'git-compare': GitCompareArrows,
  eye: Eye,
  'log-in': LogIn,
  'shield-alert': ShieldAlert,
  terminal: Terminal,
};

@Component({
  selector: 'app-nav-icon',
  standalone: true,
  imports: [LucideAngularModule],
  template: `
    @if (iconData()) {
      <lucide-icon [img]="iconData()!" [size]="size()" />
    }
  `,
  styles: [':host { display: inline-flex; align-items: center; justify-content: center; }'],
})
export class NavIconComponent {
  name = input.required<string>();
  size = input(22);

  iconData = computed(() => ICON_MAP[this.name()] ?? null);
}
