import { MODULES } from './principal';

export const ADMIN = `${MODULES.GEN.SUBS.SEGURIDAD}001`;

export const GEN_AUTHORITIES = {
  CODE: MODULES.GEN.CODE,
  ADMIN,
  HOME_OCULTO: `${MODULES.GEN.SUBS.SEGURIDAD}002`,
  PERMISOS: {
    CODE: MODULES.GEN.SUBS.PERMISOS,
    GESTIONAR_TODOS: `${MODULES.GEN.SUBS.PERMISOS}001`,
    CREAR: `${MODULES.GEN.SUBS.PERMISOS}002`,
  },
};
