import { FormControl } from '@angular/forms';
import { SafeResourceUrl } from '@angular/platform-browser';

export interface EnlaceExternoI {
  key: number;
  url: string | SafeResourceUrl;
}

export const SANITIZED = new FormControl(false);

export const ENLACES_EXTERNOS: EnlaceExternoI[] = [
  { key: 1, url: 'gen/dependencias/manage' },
  { key: 2, url: 'hpn/gestion-clinica/web/gestionar-areas' },
  { key: 3, url: 'hpn/gestion-clinica/web/administrar-gestiones' },
  { key: 4, url: 'hpn/gestion-clinica/web/administrar-traslados-ambulancia' },
  { key: 5, url: 'hpn/gestion-clinica/web/gestionar-pacientes' },
  { key: 6, url: 'hpn/gestion-clinica/web/censo-especialidades' },
  { key: 7, url: 'hpn/gestion-clinica/web/tiempos-egresos' },
  { key: 8, url: 'hpn/gestion-clinica/web/traslados-movil' },
  { key: 9, url: 'hpn/gestion-clinica/web/registrar-empleado-or-entidad' },
  { key: 10, url: 'hpn/gestion-clinica/web/turnos/entrega' },
  { key: 11, url: 'hpn/gestion-clinica/web/turnos/gestion' },
  { key: 12, url: 'hpn/valores-criticos/web/reporte' },
  { key: 13, url: 'hpn/valores-criticos/web/revision-alertas-sanitarias' },
  { key: 14, url: 'hpn/valores-criticos/web/recepcion-tecnica-reactivos' },
  { key: 15, url: 'hpn/auditoria/web/registro' },
  { key: 16, url: 'hpn/dietas/jornada' },
  { key: 17, url: 'hpn/dietas/registro' },
  { key: 18, url: 'hpn/dietas/no-recibidas' },
  { key: 19, url: 'hpn/dietas/facturacion' },
  { key: 20, url: 'hpn/camas/reservar-camas' },
  { key: 21, url: 'hpn/camas/lista-espera' },
  { key: 22, url: 'hpn/censos/pacientes' },
  { key: 23, url: 'hpn/censos/camas' },
  { key: 24, url: 'hpn/censos/revaloracion' },
  { key: 25, url: 'hpn/triage/web/tablero-triage' },
  { key: 26, url: 'hcn/balances-enfermeria/web/sabanas-uci' },
  { key: 27, url: 'hcn/balances-enfermeria/web/reporte-sabanas' },
  { key: 28, url: 'hcn/epicrisis/web/desconfirmar-epicrisis' },
  { key: 29, url: 'hcn/interconsultas/web/interconsultas-pendientes' },
  { key: 30, url: 'sln/productos/cambiar-conceptos-facturacion' },
  { key: 31, url: 'sln/reportes/web/facturacion-periodo' },
  { key: 32, url: 'sln/informes-gerenciales/facturacion-terceros' },
  { key: 33, url: 'sln/informes-gerenciales/terceros-entidad' },
  { key: 34, url: 'sln/informes-gerenciales/estadistico-pfgp' },
  { key: 35, url: 'sln/informes-gerenciales/estadistico-radicacion' },
  { key: 36, url: 'sln/control-egresos/web/egresos-facturacion' },
  { key: 37, url: 'sln/control-egresos/web/control-facturadores' },
  { key: 38, url: 'sln/validaciones/web/validacion-identificacion' },
  { key: 39, url: 'crn/gestion-conciliacion/gestiones-cartera' },
  { key: 40, url: 'crn/gestion-conciliacion/gestionar-conciliaciones' },
  { key: 41, url: 'crn/radicacion/web/facturas-radicadas' },
  { key: 42, url: 'crn/radicacion/web/facturas-pendientes-centros' },
  { key: 43, url: 'crn/radicacion/web/facturas-pendientes-verificacion' },
  { key: 44, url: 'crn/formatos/web/archivo-mega-plano' },
  { key: 45, url: 'inn/equipo-biomedico/web/hdv' },
  { key: 46, url: 'inn/equipo-biomedico/web/create-identificacion-ebm' },
  { key: 47, url: 'inn/servicio-tecnico/web/asignar-tipos-to-usuarios' },
  { key: 48, url: 'inn/servicio-tecnico/web/agregar-solicitudes' },
  { key: 49, url: 'inn/servicio-tecnico/web/atender-solicitudes' },
  { key: 54, url: 'inn/central-compras/gestionar-solicitudes' },
  { key: 55, url: 'inn/central-compras/gestionar-solicitudes-medicamentos' },
  { key: 56, url: 'inn/central-compras/generar-cotizacion' },
  { key: 57, url: 'inn/central-compras/cotizacion-prefabricada' },
  { key: 58, url: 'inn/productos/web/reporte-resumido' },
  { key: 59, url: 'inn/productos/web/reporte-oncologia' },
  { key: 60, url: 'inn/farmacia/web/productos-disponibles-x-centro' },
  { key: 61, url: 'inn/farmacia/recepciones-tecnicas/web/manage' },
  { key: 62, url: 'inn/farmacia/web/gestionar-devoluciones' },
  { key: 63, url: 'inn/farmacia/web/inventario-ciclico' },
  { key: 64, url: 'inn/farmacia/web/gestion-demandas-insatisfechas' },
  { key: 65, url: 'inn/farmacia/web/control-gasto' },
  { key: 66, url: 'inn/farmacia/web/legalizacion-factura' },
  { key: 67, url: 'inn/farmacia/web/inventario-farmacia' },
  { key: 68, url: 'inn/solicitudes-mezclas/web/oncologicos' },
  { key: 69, url: 'inn/solicitudes-mezclas/web/no-oncologicos' },
  { key: 70, url: 'inn/solicitudes-mezclas/web/nutricion-parenteral' },
  { key: 71, url: 'inn/solicitudes-mezclas/web/reenvace-tableteria' },
  { key: 72, url: 'inn/ofertas/web/productos' },
];
