import { allContexts, GCM_CONTEXTS } from '@kato-lee/utilities/types';
import { INN_AUTHORITIES } from '@authorities/legacy/inventario';
import { NavModule } from '@aside/config';
import { ADMIN } from '@auths/general';

export const LEGACY_INVENTARIO_SNAV_ITEMS: NavModule[] = [
  {
    id: 'inventario',
    label: 'Inventario',
    description: 'Gestión integral de inventarios, compras, farmacia y suministros.',
    icon: 'boxes',
    accent: 'turquoise',
    authorities: [ADMIN, INN_AUTHORITIES.CODE],
    submodules: [
      {
        id: 'equipos',
        label: 'Equipos',
        description: 'Administración de equipos biomédicos y su información técnica.',
        icon: 'cpu',
        accent: 'steel',
        authorities: [ADMIN, INN_AUTHORITIES.EQUIPO_BIOMEDICO.CODE],
        routes: [
          {
            id: 'hoja-de-vida-equipos-general',
            label: 'Hoja de Vida Equipos General',
            description: 'Consulta y gestión de la hoja de vida de los equipos biomédicos.',
            href: 'legacy/45',
            icon: 'file-text',
            authorities: [ADMIN, INN_AUTHORITIES.EQUIPO_BIOMEDICO.BASICO],
          },
          {
            id: 'creacion-identificacion-equipo',
            label: 'Creacion identificacion equipo',
            description: 'Registro e identificación de nuevos equipos biomédicos.',
            href: 'legacy/46',
            icon: 'barcode',
            authorities: [ADMIN, INN_AUTHORITIES.EQUIPO_BIOMEDICO.BASICO],
          },
        ],
      },
      {
        id: 'gestion-de-servicios',
        label: 'Gestión de servicios',
        description: 'Gestión de soporte técnico, solicitudes y mantenimiento.',
        icon: 'wrench',
        accent: 'charcoal',
        authorities: [ADMIN, INN_AUTHORITIES.SERVICIO_TECNICO.CODE],
        routes: [
          {
            id: 'asignar-tipos-a-usuarios',
            label: 'Asignar tipos a usuarios',
            description: 'Asignación de tipos de servicio a usuarios.',
            href: 'legacy/47',
            icon: 'users-cog',
            authorities: [ADMIN, INN_AUTHORITIES.SERVICIO_TECNICO.MANAGE_TIPOS_TO_USUARIOS],
          },
          {
            id: 'agregar-solicitudes',
            label: 'Agregar solicitudes',
            description: 'Creación de solicitudes de servicio técnico.',
            href: 'legacy/48',
            icon: 'plus-circle',
            authorities: [ADMIN, INN_AUTHORITIES.SERVICIO_TECNICO.AGREGAR_SOLICITUDES],
          },
          {
            id: 'atender-solicitudes',
            label: 'Atender solicitudes',
            description: 'Gestión y atención de solicitudes técnicas.',
            href: 'legacy/49',
            icon: 'headphones',
            authorities: [ADMIN, INN_AUTHORITIES.SERVICIO_TECNICO.ATENDER_SOLICITUDES],
          },
        ],
      },
      {
        id: 'central-de-compras',
        label: 'Central de compras',
        description: 'Procesos de compras, órdenes y cotizaciones.',
        icon: 'shopping-cart',
        accent: 'cream',
        authorities: [ADMIN, INN_AUTHORITIES.CENTRAL_COMPRAS.CODE],
        routes: [
          {
            id: 'gestionar-solicitudes',
            label: 'Gestionar solicitudes',
            description: 'Gestión de solicitudes de compra.',
            href: 'legacy/54',
            icon: 'clipboard-list',
            authorities: [ADMIN, INN_AUTHORITIES.CENTRAL_COMPRAS.CODE],
          },
          {
            id: 'gestion-oc-medicamentos-dispositivos',
            label: 'Gestión OC medicamentos & dispositivos',
            description: 'Gestión de órdenes de compra de medicamentos y dispositivos.',
            href: 'legacy/55',
            icon: 'file-spreadsheet',
            authorities: [ADMIN, INN_AUTHORITIES.CENTRAL_COMPRAS.CODE],
          },
          {
            id: 'generar-oc',
            label: 'Generar OC',
            description: 'Generación de órdenes de compra.',
            href: 'legacy/56',
            icon: 'file-plus',
            authorities: [ADMIN, INN_AUTHORITIES.CENTRAL_COMPRAS.COTIZACIONES_PREFABRICADAS],
          },
          {
            id: 'historico-oc-gestionadas',
            label: 'Historico OC gestionadas',
            description: 'Consulta del histórico de órdenes de compra.',
            href: 'legacy/57',
            icon: 'history',
            authorities: [ADMIN, INN_AUTHORITIES.CENTRAL_COMPRAS.COTIZACIONES_PREFABRICADAS],
          },
        ],
      },
      {
        id: 'farmacia',
        label: 'Farmacia',
        description: 'Gestión de farmacia, inventarios y suministros clínicos.',
        icon: 'pill',
        accent: 'ice',
        authorities: [
          ADMIN,
          INN_AUTHORITIES.FARMACIA.CODE,
          INN_AUTHORITIES.RECEPCION_TECNICA.CODE,
          INN_AUTHORITIES.PRODUCTOS.CODE,
          INN_AUTHORITIES.SUMINISTROS.CODE,
        ],
        routes: [
          {
            id: 'productos-disponibles-x-farmacia',
            label: 'Productos disponibles x farmacia',
            description: 'Consulta de productos disponibles por farmacia.',
            href: 'legacy/58',
            icon: 'package',
            authorities: [ADMIN, INN_AUTHORITIES.PRODUCTOS.GESTION_REPORTES],
          },
          {
            id: 'productos-disponibles-oncologia',
            label: 'Productos disponibles (oncología)',
            description: 'Consulta de productos disponibles para oncología.',
            href: 'legacy/59',
            icon: 'biohazard',
            disableOnContexts: allContexts([GCM_CONTEXTS.ALTACENTRO]).codes,
            authorities: [ADMIN, INN_AUTHORITIES.PRODUCTOS.GESTION_REPORTES],
          },
          {
            id: 'productos-disponibles-por-centro',
            label: 'Productos disponibles (por centro)',
            description: 'Consulta de productos disponibles por centro médico.',
            href: 'legacy/60',
            icon: 'map-pin',
            authorities: [ADMIN, INN_AUTHORITIES.PRODUCTOS.GESTION_REPORTES],
          },
          {
            id: 'gestionar-recepciones-tecnicas',
            label: 'Gestionar recepciones tecnicas',
            description: 'Gestión de recepciones técnicas de productos.',
            href: 'legacy/61',
            icon: 'inbox',
            authorities: [ADMIN, INN_AUTHORITIES.RECEPCION_TECNICA.GENERAR_CONSULTAR_RECEPC_TECN],
          },
          {
            id: 'gestionar-devoluciones-de-mezclas',
            label: 'Gestionar devoluciones de mezclas',
            description: 'Gestión de devoluciones de mezclas farmacéuticas.',
            href: 'legacy/62',
            icon: 'undo-2',
            authorities: [ADMIN, INN_AUTHORITIES.SUMINISTROS.GESTION_SUM_MEZCLA_DEV],
          },
          {
            id: 'inventario-ciclico',
            label: 'Inventario cíclico',
            description: 'Control periódico del inventario farmacéutico.',
            href: 'legacy/63',
            icon: 'repeat',
            authorities: [
              ADMIN,
              INN_AUTHORITIES.FARMACIA.GESTION_INVENTARIO_CICLICO,
              INN_AUTHORITIES.FARMACIA.VERIFICAR_INVENTARIO_CICLICO,
            ],
          },
          {
            id: 'gestion-demandas-insatisfechas',
            label: 'Gestión demandas insatisfechas',
            description: 'Gestión de demandas de medicamentos no satisfechas.',
            href: 'legacy/64',
            icon: 'alert-circle',
            authorities: [ADMIN, INN_AUTHORITIES.FARMACIA.GESTION_DEMANDAS_INSATISFECHAS],
          },
          {
            id: 'control-de-gasto-en-consignacion',
            label: 'Control de gasto en consignación',
            description: 'Control de gastos asociados a consignación.',
            href: 'legacy/65',
            icon: 'dollar-sign',
            authorities: [
              ADMIN,
              INN_AUTHORITIES.FARMACIA.CONTROL_GASTOS_FACTURADOR,
              INN_AUTHORITIES.FARMACIA.CONTROL_GASTOS_SOLICITANTE,
            ],
          },
          {
            id: 'legalizacion-de-facturas',
            label: 'Legalización de facturas',
            description: 'Proceso de legalización de facturas de farmacia.',
            href: 'legacy/66',
            icon: 'file-check',
            authorities: [
              ADMIN,
              INN_AUTHORITIES.FARMACIA.LEGALIZACION_FACTURAS_FACTURADOR,
              INN_AUTHORITIES.FARMACIA.LEGALIZACION_FACTURAS_SOLICITANTE,
            ],
          },
          {
            id: 'inventario',
            label: 'Inventario',
            description: 'Consulta y administración del inventario farmacéutico.',
            href: 'legacy/67',
            icon: 'boxes',
            authorities: [
              ADMIN,
              INN_AUTHORITIES.FARMACIA.INVENTARIO_ADMIN,
              INN_AUTHORITIES.FARMACIA.INVENTARIO_CONTEO,
            ],
          },
        ],
      },
      {
        id: 'solicitudes-de-preparacion-a-central',
        label: 'Solicitudes de preparación a central',
        description: 'Gestión de solicitudes de preparación de mezclas.',
        icon: 'flask-conical',
        accent: 'blood',
        authorities: [ADMIN, INN_AUTHORITIES.SOLICITUDES_MEZCLAS.CODE],
        routes: [
          {
            id: 'oncologicos',
            label: 'Oncológicos',
            description: 'Solicitudes de preparación oncológica.',
            href: 'legacy/68',
            icon: 'syringe',
            authorities: [ADMIN, INN_AUTHORITIES.SOLICITUDES_MEZCLAS.GESTION_SOLICITUDES],
          },
          {
            id: 'no-oncologicos',
            label: 'No oncológicos',
            description: 'Solicitudes de preparación no oncológica.',
            href: 'legacy/69',
            icon: 'flask-round',
            authorities: [ADMIN, INN_AUTHORITIES.SOLICITUDES_MEZCLAS.GESTION_SOLICITUDES],
          },
          {
            id: 'nutricion-parenteral',
            label: 'Nutrición parenteral',
            description: 'Solicitudes de nutrición parenteral.',
            href: 'legacy/70',
            icon: 'beaker',
            authorities: [ADMIN, INN_AUTHORITIES.SOLICITUDES_MEZCLAS.GESTION_SOLICITUDES],
          },
          {
            id: 'reempaque-reenvace-de-tableteria',
            label: 'Reempaque / reenvace de tabletería',
            description: 'Solicitudes de reempaque y reenvasado de tabletería.',
            href: 'legacy/71',
            icon: 'package-open',
            authorities: [ADMIN, INN_AUTHORITIES.SOLICITUDES_MEZCLAS.GESTION_SOLICITUDES],
          },
        ],
      },
      {
        id: 'ofertas',
        label: 'Ofertas',
        description: 'Gestión de ofertas comerciales de productos.',
        icon: 'badge-percent',
        accent: 'sun',
        authorities: [ADMIN, INN_AUTHORITIES.OFERTAS.CODE],
        routes: [
          {
            id: 'productos',
            label: 'productos',
            description: 'Listado y gestión de productos en oferta.',
            href: 'legacy/72',
            icon: 'tag',
            authorities: [ADMIN, INN_AUTHORITIES.OFERTAS.LISTAR],
          },
        ],
      },
    ],
  },
];
