import { MODULES } from './principal';

export const CRN_AUTHORITIES = {
  CODE: MODULES.CRN.CODE,
  GESTIONES_CONCILIACIONES: {
    CODE: MODULES.CRN.SUBS.GESTIONES_CONCILIACIONES,
    ADMINISTRAR_GESTIONES: `${MODULES.CRN.SUBS.GESTIONES_CONCILIACIONES}001`,
    ADMINISTRAR_CONCILIACIONES: `${MODULES.CRN.SUBS.GESTIONES_CONCILIACIONES}002`,
    ELIMINAR_GESTION_CONCILIACION: `${MODULES.CRN.SUBS.GESTIONES_CONCILIACIONES}003`,
  },
  RADICACIONES: {
    CODE: MODULES.CRN.SUBS.RADICACIONES,
    GESTIONAR_RADICACIONES_GCM: `${MODULES.CRN.SUBS.RADICACIONES}001`,
  },
  FORMATOS: {
    CODE: MODULES.CRN.SUBS.FORMATOS,
    ARCHIVO_MEGA_PLANO: `${MODULES.CRN.SUBS.FORMATOS}001`,
  },
};
