import { MODULES } from './principal';

export const SLN_AUTHORITIES = {
  CODE: MODULES.SLN.CODE,
  INFORMES_GERENCIALES: {
    CODE: MODULES.SLN.SUBS.INFORMES_GERENCIALES,
    FACTURACION_PERIODO: `${MODULES.SLN.SUBS.INFORMES_GERENCIALES}001`,
    ESTADISTICO_PFGP: `${MODULES.SLN.SUBS.INFORMES_GERENCIALES}002`,
    ESTADISTICO_RADICACION: `${MODULES.SLN.SUBS.INFORMES_GERENCIALES}003`,
    FACTURACION_TERCEROS: `${MODULES.SLN.SUBS.INFORMES_GERENCIALES}004`,
    PUEDE_VER_X_FACT_ENTIDADES: `${MODULES.SLN.SUBS.INFORMES_GERENCIALES}005`,
    FACT_TERCEROS_INSTITUCION: `${MODULES.SLN.SUBS.INFORMES_GERENCIALES}006`,
  },
  PRODUCTOS: {
    CODE: MODULES.SLN.SUBS.PRODUCTOS,
    CAMBIAR_CONCEPTO_FACTURACION: `${MODULES.SLN.SUBS.PRODUCTOS}001`,
  },
  CONTROL_EGRESOS: {
    CODE: MODULES.SLN.SUBS.CONTROL_EGRESOS,
    CREAR_PENDIENTES: `${MODULES.SLN.SUBS.CONTROL_EGRESOS}001`,
    ASIGNAR_USUARIO: `${MODULES.SLN.SUBS.CONTROL_EGRESOS}002`,
    VER_EGRESOS: `${MODULES.SLN.SUBS.CONTROL_EGRESOS}003`,
  },
  VALIDACIONES: {
    CODE: MODULES.SLN.SUBS.VALIDACIONES,
    VALIDAR_ID: `${MODULES.SLN.SUBS.VALIDACIONES}001`,
  },
};
