import { MODULES } from './principal';

export const GEN_AUTHORITIES = {
  CODE: MODULES.GEN.CODE,
  ADMIN: `${MODULES.GEN.SUBS.SEGURIDAD}001`,
  HOME_OCULTO: `${MODULES.GEN.SUBS.SEGURIDAD}002`,
  GEMI: `${MODULES.GMN.CODE}001001`,
  PERMISOS: {
    CODE: MODULES.GEN.SUBS.PERMISOS,
    GESTIONAR_TODOS: `${MODULES.GEN.SUBS.PERMISOS}001`,
    CREAR: `${MODULES.GEN.SUBS.PERMISOS}002`,
  },
  DEPENDENCIAS: {
    CODE: MODULES.GEN.SUBS.DEPENDENCIAS,
    GESTIONAR: `${MODULES.GEN.SUBS.DEPENDENCIAS}001`,
    INACTIVO_2: `${MODULES.GEN.SUBS.DEPENDENCIAS}002`,
    INACTIVO_3: `${MODULES.GEN.SUBS.DEPENDENCIAS}003`,
  },
};
