import { Component, input, computed } from '@angular/core';
import {
  type LucideIconData,
  LucideAngularModule,
  ShieldCheck,
  Lock,
  Layers,
  Users,
  FolderCog,
  ChartNoAxesCombined,
  X,
  Activity,
  Settings,
  Hospital,
  Stethoscope,
  AlertTriangle,
  Utensils,
  Bed,
  BarChart2,
  Building2,
  ClipboardList,
  Ambulance,
  BarChart3,
  Timer,
  Truck,
  UserPlus,
  RotateCw,
  CalendarClock,
  FileText,
  BellRing,
  FlaskConical,
  ListChecks,
  Clock,
  ClipboardEdit,
  XCircle,
  Receipt,
  BedDouble,
  Hourglass,
  UsersRound,
  RefreshCw,
  LayoutDashboard,
  MessageSquarePlus,
  Undo2,
  Package,
  LogOut,
  Settings2,
  CalendarRange,
  LineChart,
  FileBarChart,
  ClipboardCheck,
  IdCard,
  Wallet,
  Handshake,
  Send,
  FileSpreadsheet,
  Scale,
  FileCheck,
  FileClock,
  Inbox,
  Upload,
  Boxes,
  Cpu,
  Wrench,
  ShoppingCart,
  Pill,
  BadgePercent,
  Barcode,
  UserCog,
  PlusCircle,
  Headphones,
  FilePlus,
  History,
  Biohazard,
  MapPin,
  Repeat,
  AlertCircle,
  DollarSign,
  Syringe,
  FlaskRound,
  Beaker,
  PackageOpen,
  Tag,
} from 'lucide-angular';

/**
 * Mapa de iconos keyed por su nombre kebab-case.
 * Para agregar un icono nuevo, solo importalo arriba y registralo aqui.
 */
const ICON_MAP: Record<string, LucideIconData> = {
  'shield-check': ShieldCheck,
  lock: Lock,
  layers: Layers,
  'user-cog': UserCog,
  users: Users,
  'folder-cog': FolderCog,
  'chart-no-axes-combined': ChartNoAxesCombined,
  x: X,
  activity: Activity,
  settings: Settings,
  hospital: Hospital,
  stethoscope: Stethoscope,
  'alert-triangle': AlertTriangle,
  utensils: Utensils,
  bed: Bed,
  'bar-chart-2': BarChart2,
  'building-2': Building2,
  'clipboard-list': ClipboardList,
  ambulance: Ambulance,
  'bar-chart-3': BarChart3,
  timer: Timer,
  truck: Truck,
  'user-plus': UserPlus,
  'rotate-cw': RotateCw,
  'calendar-clock': CalendarClock,
  'file-text': FileText,
  'bell-ring': BellRing,
  'flask-conical': FlaskConical,
  'list-checks': ListChecks,
  clock: Clock,
  'clipboard-edit': ClipboardEdit,
  'x-circle': XCircle,
  receipt: Receipt,
  'bed-double': BedDouble,
  hourglass: Hourglass,
  'users-round': UsersRound,
  'refresh-cw': RefreshCw,
  'layout-dashboard': LayoutDashboard,
  'file-medical': FileText,
  'book-medical': ClipboardList,
  'message-square-plus': MessageSquarePlus,
  'undo-2': Undo2,
  package: Package,
  'log-out': LogOut,
  'settings-2': Settings2,
  'calendar-range': CalendarRange,
  'line-chart': LineChart,
  'file-bar-chart': FileBarChart,
  'clipboard-check': ClipboardCheck,
  'id-card': IdCard,
  wallet: Wallet,
  handshake: Handshake,
  send: Send,
  'file-spreadsheet': FileSpreadsheet,
  scale: Scale,
  'file-check': FileCheck,
  'file-clock': FileClock,
  inbox: Inbox,
  upload: Upload,
  boxes: Boxes,
  cpu: Cpu,
  wrench: Wrench,
  'shopping-cart': ShoppingCart,
  pill: Pill,
  'badge-percent': BadgePercent,
  barcode: Barcode,
  'users-cog': UserCog,
  'plus-circle': PlusCircle,
  headphones: Headphones,
  'file-plus': FilePlus,
  history: History,
  biohazard: Biohazard,
  'map-pin': MapPin,
  repeat: Repeat,
  'alert-circle': AlertCircle,
  'dollar-sign': DollarSign,
  syringe: Syringe,
  'flask-round': FlaskRound,
  beaker: Beaker,
  'package-open': PackageOpen,
  tag: Tag,
};

@Component({
  selector: 'app-nav-icon',
  imports: [LucideAngularModule],
  template: `
    @if (iconData()) {
      <lucide-icon [img]="iconData()!" [size]="size()" />
    }
  `,
  styles: [':host { display: inline-flex; align-items: center; justify-content: center; }'],
})
export class NavIconComponent {
  name = input.required<string>();
  size = input(22);

  iconData = computed(() => ICON_MAP[this.name()] ?? null);
}
